/*
 * mt_version.hh
 *
 *  Generated by cmake from mt_version.hh.in
 *
 *  Created on: Mar 20, 2013
 *      Author: nsoblath
 */

#ifndef MT_VERSION_HH_
#define MT_VERSION_HH_

#include "scarab_version.hh"

#include "mt_api.hh"

namespace mantis
{
    class MANTIS_API version : public scarab::version_semantic
    {
        public:
            version();
            ~version();
    };

} // namespace mantis

#endif /* MT_VERSION_HH_ */
